import type { Character } from '../engine/types';

export const characters: Character[] = [
  {
    id: 'spider-man',
    name: 'Spider-Man',
    aliases: ['spidey'],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/spider-man-1.svg', style: 'comic' },
      { file: 'pictures/spider-man-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'iron-man',
    name: 'Iron Man',
    aliases: ['tony stark'],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/iron-man-1.svg', style: 'comic' },
      { file: 'pictures/iron-man-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'captain-america',
    name: 'Captain America',
    aliases: ['cap'],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/captain-america-1.svg', style: 'comic' },
      { file: 'pictures/captain-america-2.svg', style: 'movie' },
      { file: 'pictures/captain-america-3.svg', style: 'cartoon' },
    ],
  },
  {
    id: 'hulk',
    name: 'Hulk',
    aliases: ['the hulk'],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/hulk-1.svg', style: 'comic' },
      { file: 'pictures/hulk-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'thor',
    name: 'Thor',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/thor-1.svg', style: 'comic' },
      { file: 'pictures/thor-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'black-panther',
    name: 'Black Panther',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/black-panther-1.svg', style: 'comic' },
      { file: 'pictures/black-panther-2.svg', style: 'movie' },
      { file: 'pictures/black-panther-3.svg', style: 'cartoon' },
    ],
  },
  {
    id: 'thanos',
    name: 'Thanos',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/thanos-1.svg', style: 'comic' },
      { file: 'pictures/thanos-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'loki',
    name: 'Loki',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/loki-1.svg', style: 'comic' },
      { file: 'pictures/loki-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'venom',
    name: 'Venom',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/venom-1.svg', style: 'comic' },
      { file: 'pictures/venom-2.svg', style: 'movie' },
      { file: 'pictures/venom-3.svg', style: 'cartoon' },
    ],
  },
  {
    id: 'green-goblin',
    name: 'Green Goblin',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/green-goblin-1.svg', style: 'comic' },
      { file: 'pictures/green-goblin-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'black-widow',
    name: 'Black Widow',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/black-widow-1.svg', style: 'comic' },
      { file: 'pictures/black-widow-2.svg', style: 'movie' },
      { file: 'pictures/black-widow-3.svg', style: 'cartoon' },
    ],
  },
  {
    id: 'doctor-strange',
    name: 'Doctor Strange',
    aliases: ['dr strange'],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/doctor-strange-1.svg', style: 'comic' },
      { file: 'pictures/doctor-strange-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'ultron',
    name: 'Ultron',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/ultron-1.svg', style: 'comic' },
      { file: 'pictures/ultron-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'doctor-doom',
    name: 'Doctor Doom',
    aliases: ['dr doom', 'victor von doom'],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/doctor-doom-1.svg', style: 'comic' },
      { file: 'pictures/doctor-doom-2.svg', style: 'movie' },
      { file: 'pictures/doctor-doom-3.svg', style: 'cartoon' },
    ],
  },
  {
    id: 'hawkeye',
    name: 'Hawkeye',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/hawkeye-1.svg', style: 'comic' },
      { file: 'pictures/hawkeye-2.svg', style: 'movie' },
      { file: 'pictures/hawkeye-3.svg', style: 'cartoon' },
    ],
  },
  {
    id: 'nightcrawler',
    name: 'Nightcrawler',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/nightcrawler-1.svg', style: 'comic' },
      { file: 'pictures/nightcrawler-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'mystique',
    name: 'Mystique',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/mystique-1.svg', style: 'comic' },
      { file: 'pictures/mystique-2.svg', style: 'movie' },
    ],
  },
  {
    id: 'kingpin',
    name: 'Kingpin',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/kingpin-1.svg', style: 'comic' },
      { file: 'pictures/kingpin-2.svg', style: 'movie' },
      { file: 'pictures/kingpin-3.svg', style: 'cartoon' },
    ],
  },
];
