import type { Character } from '../engine/types';

export const characters: Character[] = [
  {
    id: 'spider-man',
    name: 'Spider-Man',
    aliases: ['spidey'],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/spider-man-1.webp', style: 'comic' },
      { file: 'pictures/spider-man-2.webp', style: 'movie' },
      { file: 'pictures/spider-man-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'iron-man',
    name: 'Iron Man',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/iron-man-1.webp', style: 'comic' },
      { file: 'pictures/iron-man-2.webp', style: 'comic' },
      { file: 'pictures/iron-man-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'captain-america',
    name: 'Captain America',
    aliases: ['cap'],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/captain-america-1.webp', style: 'movie' },
      { file: 'pictures/captain-america-2.webp', style: 'movie' },
      { file: 'pictures/captain-america-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'hulk',
    name: 'Hulk',
    aliases: ['the hulk'],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/hulk-1.webp', style: 'movie' },
      { file: 'pictures/hulk-2.webp', style: 'cartoon' },
      { file: 'pictures/hulk-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'thor',
    name: 'Thor',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/thor-1.webp', style: 'movie' },
      { file: 'pictures/thor-2.webp', style: 'cartoon' },
      { file: 'pictures/thor-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'black-panther',
    name: 'Black Panther',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/black-panther-1.webp', style: 'movie' },
      { file: 'pictures/black-panther-2.webp', style: 'cartoon' },
      { file: 'pictures/black-panther-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'wolverine',
    name: 'Wolverine',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/wolverine-1.webp', style: 'movie' },
      { file: 'pictures/wolverine-2.webp', style: 'cartoon' },
      { file: 'pictures/wolverine-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'deadpool',
    name: 'Deadpool',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/deadpool-1.webp', style: 'comic' },
      { file: 'pictures/deadpool-2.webp', style: 'cartoon' },
      { file: 'pictures/deadpool-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'black-widow',
    name: 'Black Widow',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/black-widow-1.webp', style: 'movie' },
      { file: 'pictures/black-widow-2.webp', style: 'movie' },
      { file: 'pictures/black-widow-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'captain-marvel',
    name: 'Captain Marvel',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/captain-marvel-1.webp', style: 'comic' },
      { file: 'pictures/captain-marvel-2.webp', style: 'movie' },
      { file: 'pictures/captain-marvel-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'ant-man',
    name: 'Ant-Man',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/ant-man-1.webp', style: 'comic' },
      { file: 'pictures/ant-man-2.webp', style: 'comic' },
      { file: 'pictures/ant-man-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'doctor-strange',
    name: 'Doctor Strange',
    aliases: ['dr strange'],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/doctor-strange-1.webp', style: 'comic' },
      { file: 'pictures/doctor-strange-2.webp', style: 'movie' },
      { file: 'pictures/doctor-strange-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'scarlet-witch',
    name: 'Scarlet Witch',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/scarlet-witch-1.webp', style: 'comic' },
      { file: 'pictures/scarlet-witch-2.webp', style: 'comic' },
      { file: 'pictures/scarlet-witch-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'groot',
    name: 'Groot',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/groot-1.webp', style: 'comic' },
      { file: 'pictures/groot-2.webp', style: 'movie' },
      { file: 'pictures/groot-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'rocket-raccoon',
    name: 'Rocket Raccoon',
    aliases: ['rocket'],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/rocket-raccoon-1.webp', style: 'comic' },
      { file: 'pictures/rocket-raccoon-2.webp', style: 'movie' },
      { file: 'pictures/rocket-raccoon-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'daredevil',
    name: 'Daredevil',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/daredevil-1.webp', style: 'comic' },
      { file: 'pictures/daredevil-2.webp', style: 'movie' },
      { file: 'pictures/daredevil-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'star-lord',
    name: 'Star-Lord',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/star-lord-1.webp', style: 'comic' },
      { file: 'pictures/star-lord-2.webp', style: 'movie' },
      { file: 'pictures/star-lord-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'falcon',
    name: 'Falcon',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/falcon-1.webp', style: 'comic' },
      { file: 'pictures/falcon-2.webp', style: 'comic' },
      { file: 'pictures/falcon-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'storm',
    name: 'Storm',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/storm-1.webp', style: 'comic' },
      { file: 'pictures/storm-2.webp', style: 'cartoon' },
      { file: 'pictures/storm-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'vision',
    name: 'Vision',
    aliases: [],
    tier: 'rookie',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/vision-1.webp', style: 'comic' },
      { file: 'pictures/vision-2.webp', style: 'comic' },
      { file: 'pictures/vision-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'thanos',
    name: 'Thanos',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/thanos-1.webp', style: 'comic' },
      { file: 'pictures/thanos-2.webp', style: 'movie' },
      { file: 'pictures/thanos-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'loki',
    name: 'Loki',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/loki-1.webp', style: 'comic' },
      { file: 'pictures/loki-2.webp', style: 'cartoon' },
      { file: 'pictures/loki-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'venom',
    name: 'Venom',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/venom-1.webp', style: 'comic' },
      { file: 'pictures/venom-2.webp', style: 'comic' },
      { file: 'pictures/venom-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'green-goblin',
    name: 'Green Goblin',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/green-goblin-1.webp', style: 'movie' },
      { file: 'pictures/green-goblin-2.webp', style: 'movie' },
      { file: 'pictures/green-goblin-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'ultron',
    name: 'Ultron',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/ultron-1.webp', style: 'comic' },
      { file: 'pictures/ultron-2.webp', style: 'movie' },
      { file: 'pictures/ultron-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'doctor-doom',
    name: 'Doctor Doom',
    aliases: ['dr doom', 'doom'],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/doctor-doom-1.webp', style: 'comic' },
      { file: 'pictures/doctor-doom-2.webp', style: 'comic' },
      { file: 'pictures/doctor-doom-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'red-skull',
    name: 'Red Skull',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/red-skull-1.webp', style: 'comic' },
      { file: 'pictures/red-skull-2.webp', style: 'movie' },
      { file: 'pictures/red-skull-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'magneto',
    name: 'Magneto',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/magneto-1.webp', style: 'comic' },
      { file: 'pictures/magneto-2.webp', style: 'comic' },
      { file: 'pictures/magneto-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'doctor-octopus',
    name: 'Doctor Octopus',
    aliases: ['doc ock', 'dr octopus'],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/doctor-octopus-1.webp', style: 'comic' },
      { file: 'pictures/doctor-octopus-2.webp', style: 'comic' },
      { file: 'pictures/doctor-octopus-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'killmonger',
    name: 'Killmonger',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/killmonger-1.webp', style: 'comic' },
      { file: 'pictures/killmonger-2.webp', style: 'comic' },
      { file: 'pictures/killmonger-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'hela',
    name: 'Hela',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/hela-1.webp', style: 'movie' },
      { file: 'pictures/hela-2.webp', style: 'movie' },
      { file: 'pictures/hela-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'mysterio',
    name: 'Mysterio',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/mysterio-1.webp', style: 'comic' },
      { file: 'pictures/mysterio-2.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'carnage',
    name: 'Carnage',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/carnage-1.webp', style: 'comic' },
      { file: 'pictures/carnage-2.webp', style: 'comic' },
      { file: 'pictures/carnage-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'vulture',
    name: 'Vulture',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/vulture-1.webp', style: 'comic' },
      { file: 'pictures/vulture-2.webp', style: 'comic' },
      { file: 'pictures/vulture-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'sandman',
    name: 'Sandman',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/sandman-1.webp', style: 'movie' },
      { file: 'pictures/sandman-2.webp', style: 'movie' },
      { file: 'pictures/sandman-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'electro',
    name: 'Electro',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/electro-1.webp', style: 'comic' },
      { file: 'pictures/electro-2.webp', style: 'movie' },
      { file: 'pictures/electro-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'kingpin',
    name: 'Kingpin',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/kingpin-1.webp', style: 'comic' },
      { file: 'pictures/kingpin-2.webp', style: 'movie' },
      { file: 'pictures/kingpin-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'mystique',
    name: 'Mystique',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/mystique-1.webp', style: 'movie' },
      { file: 'pictures/mystique-2.webp', style: 'cartoon' },
      { file: 'pictures/mystique-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'lizard',
    name: 'Lizard',
    aliases: ['the lizard'],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/lizard-1.webp', style: 'comic' },
      { file: 'pictures/lizard-2.webp', style: 'cartoon' },
      { file: 'pictures/lizard-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'rhino',
    name: 'Rhino',
    aliases: [],
    tier: 'rookie',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/rhino-1.webp', style: 'comic' },
      { file: 'pictures/rhino-2.webp', style: 'comic' },
      { file: 'pictures/rhino-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'hawkeye',
    name: 'Hawkeye',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/hawkeye-1.webp', style: 'comic' },
      { file: 'pictures/hawkeye-2.webp', style: 'comic' },
      { file: 'pictures/hawkeye-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'cyclops',
    name: 'Cyclops',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/cyclops-1.webp', style: 'movie' },
      { file: 'pictures/cyclops-2.webp', style: 'cartoon' },
      { file: 'pictures/cyclops-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'jean-grey',
    name: 'Jean Grey',
    aliases: ['phoenix'],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/jean-grey-1.webp', style: 'comic' },
      { file: 'pictures/jean-grey-2.webp', style: 'movie' },
      { file: 'pictures/jean-grey-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'rogue',
    name: 'Rogue',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/rogue-1.webp', style: 'comic' },
      { file: 'pictures/rogue-2.webp', style: 'cartoon' },
      { file: 'pictures/rogue-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'gambit',
    name: 'Gambit',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/gambit-1.webp', style: 'movie' },
      { file: 'pictures/gambit-2.webp', style: 'cartoon' },
      { file: 'pictures/gambit-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'beast',
    name: 'Beast',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/beast-1.webp', style: 'movie' },
      { file: 'pictures/beast-2.webp', style: 'movie' },
      { file: 'pictures/beast-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'nick-fury',
    name: 'Nick Fury',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/nick-fury-1.webp', style: 'comic' },
      { file: 'pictures/nick-fury-2.webp', style: 'movie' },
      { file: 'pictures/nick-fury-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'winter-soldier',
    name: 'Winter Soldier',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/winter-soldier-1.webp', style: 'cartoon' },
      { file: 'pictures/winter-soldier-2.webp', style: 'comic' },
      { file: 'pictures/winter-soldier-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'war-machine',
    name: 'War Machine',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/war-machine-1.webp', style: 'movie' },
      { file: 'pictures/war-machine-2.webp', style: 'cartoon' },
      { file: 'pictures/war-machine-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'punisher',
    name: 'Punisher',
    aliases: ['the punisher'],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/punisher-1.webp', style: 'comic' },
      { file: 'pictures/punisher-2.webp', style: 'movie' },
      { file: 'pictures/punisher-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'ghost-rider',
    name: 'Ghost Rider',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/ghost-rider-1.webp', style: 'comic' },
      { file: 'pictures/ghost-rider-2.webp', style: 'movie' },
      { file: 'pictures/ghost-rider-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'silver-surfer',
    name: 'Silver Surfer',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/silver-surfer-1.webp', style: 'comic' },
      { file: 'pictures/silver-surfer-2.webp', style: 'cartoon' },
      { file: 'pictures/silver-surfer-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'quicksilver',
    name: 'Quicksilver',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/quicksilver-1.webp', style: 'comic' },
      { file: 'pictures/quicksilver-2.webp', style: 'movie' },
      { file: 'pictures/quicksilver-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'shang-chi',
    name: 'Shang-Chi',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/shang-chi-1.webp', style: 'comic' },
      { file: 'pictures/shang-chi-2.webp', style: 'movie' },
      { file: 'pictures/shang-chi-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'moon-knight',
    name: 'Moon Knight',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/moon-knight-1.webp', style: 'movie' },
      { file: 'pictures/moon-knight-2.webp', style: 'cartoon' },
      { file: 'pictures/moon-knight-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'ms-marvel',
    name: 'Ms. Marvel',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/ms-marvel-1.webp', style: 'comic' },
      { file: 'pictures/ms-marvel-2.webp', style: 'movie' },
      { file: 'pictures/ms-marvel-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'she-hulk',
    name: 'She-Hulk',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/she-hulk-1.webp', style: 'comic' },
      { file: 'pictures/she-hulk-2.webp', style: 'cartoon' },
      { file: 'pictures/she-hulk-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'gamora',
    name: 'Gamora',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/gamora-1.webp', style: 'comic' },
      { file: 'pictures/gamora-2.webp', style: 'comic' },
      { file: 'pictures/gamora-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'drax',
    name: 'Drax',
    aliases: ['drax the destroyer'],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/drax-1.webp', style: 'comic' },
      { file: 'pictures/drax-2.webp', style: 'comic' },
      { file: 'pictures/drax-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'wasp',
    name: 'Wasp',
    aliases: [],
    tier: 'pro',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/wasp-1.webp', style: 'comic' },
      { file: 'pictures/wasp-2.webp', style: 'cartoon' },
      { file: 'pictures/wasp-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'bullseye',
    name: 'Bullseye',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/bullseye-1.webp', style: 'comic' },
      { file: 'pictures/bullseye-2.webp', style: 'comic' },
      { file: 'pictures/bullseye-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'galactus',
    name: 'Galactus',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/galactus-1.webp', style: 'comic' },
      { file: 'pictures/galactus-2.webp', style: 'comic' },
      { file: 'pictures/galactus-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'apocalypse',
    name: 'Apocalypse',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/apocalypse-1.webp', style: 'comic' },
      { file: 'pictures/apocalypse-2.webp', style: 'comic' },
      { file: 'pictures/apocalypse-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'sabretooth',
    name: 'Sabretooth',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/sabretooth-1.webp', style: 'movie' },
      { file: 'pictures/sabretooth-2.webp', style: 'cartoon' },
      { file: 'pictures/sabretooth-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'juggernaut',
    name: 'Juggernaut',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/juggernaut-1.webp', style: 'comic' },
      { file: 'pictures/juggernaut-2.webp', style: 'movie' },
      { file: 'pictures/juggernaut-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'taskmaster',
    name: 'Taskmaster',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/taskmaster-1.webp', style: 'comic' },
      { file: 'pictures/taskmaster-2.webp', style: 'movie' },
      { file: 'pictures/taskmaster-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'abomination',
    name: 'Abomination',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/abomination-1.webp', style: 'movie' },
      { file: 'pictures/abomination-2.webp', style: 'movie' },
      { file: 'pictures/abomination-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'baron-zemo',
    name: 'Baron Zemo',
    aliases: ['zemo'],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/baron-zemo-1.webp', style: 'comic' },
      { file: 'pictures/baron-zemo-2.webp', style: 'movie' },
      { file: 'pictures/baron-zemo-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'crossbones',
    name: 'Crossbones',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/crossbones-1.webp', style: 'movie' },
      { file: 'pictures/crossbones-2.webp', style: 'movie' },
      { file: 'pictures/crossbones-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'dormammu',
    name: 'Dormammu',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/dormammu-1.webp', style: 'comic' },
      { file: 'pictures/dormammu-2.webp', style: 'comic' },
      { file: 'pictures/dormammu-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'ronan',
    name: 'Ronan',
    aliases: ['ronan the accuser'],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/ronan-1.webp', style: 'comic' },
      { file: 'pictures/ronan-2.webp', style: 'movie' },
      { file: 'pictures/ronan-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'nebula',
    name: 'Nebula',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/nebula-1.webp', style: 'comic' },
      { file: 'pictures/nebula-2.webp', style: 'movie' },
      { file: 'pictures/nebula-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'kang',
    name: 'Kang',
    aliases: ['kang the conqueror'],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/kang-1.webp', style: 'comic' },
      { file: 'pictures/kang-2.webp', style: 'movie' },
      { file: 'pictures/kang-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'mephisto',
    name: 'Mephisto',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/mephisto-1.webp', style: 'comic' },
      { file: 'pictures/mephisto-2.webp', style: 'comic' },
      { file: 'pictures/mephisto-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'shocker',
    name: 'Shocker',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/shocker-1.webp', style: 'movie' },
      { file: 'pictures/shocker-2.webp', style: 'movie' },
      { file: 'pictures/shocker-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'scorpion',
    name: 'Scorpion',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/scorpion-1.webp', style: 'comic' },
      { file: 'pictures/scorpion-2.webp', style: 'comic' },
      { file: 'pictures/scorpion-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'kraven',
    name: 'Kraven',
    aliases: ['kraven the hunter'],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/kraven-1.webp', style: 'comic' },
      { file: 'pictures/kraven-2.webp', style: 'comic' },
      { file: 'pictures/kraven-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'whiplash',
    name: 'Whiplash',
    aliases: [],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/whiplash-1.webp', style: 'comic' },
      { file: 'pictures/whiplash-2.webp', style: 'movie' },
      { file: 'pictures/whiplash-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'ego',
    name: 'Ego',
    aliases: ['ego the living planet'],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/ego-1.webp', style: 'comic' },
      { file: 'pictures/ego-2.webp', style: 'comic' },
      { file: 'pictures/ego-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'arnim-zola',
    name: 'Arnim Zola',
    aliases: ['zola'],
    tier: 'pro',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/arnim-zola-1.webp', style: 'comic' },
      { file: 'pictures/arnim-zola-2.webp', style: 'comic' },
      { file: 'pictures/arnim-zola-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'nightcrawler',
    name: 'Nightcrawler',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/nightcrawler-1.webp', style: 'comic' },
      { file: 'pictures/nightcrawler-2.webp', style: 'comic' },
      { file: 'pictures/nightcrawler-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'colossus',
    name: 'Colossus',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/colossus-1.webp', style: 'comic' },
      { file: 'pictures/colossus-2.webp', style: 'comic' },
      { file: 'pictures/colossus-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'cable',
    name: 'Cable',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/cable-1.webp', style: 'comic' },
      { file: 'pictures/cable-2.webp', style: 'cartoon' },
      { file: 'pictures/cable-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'nova',
    name: 'Nova',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/nova-1.webp', style: 'comic' },
      { file: 'pictures/nova-2.webp', style: 'comic' },
      { file: 'pictures/nova-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'black-bolt',
    name: 'Black Bolt',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/black-bolt-1.webp', style: 'comic' },
      { file: 'pictures/black-bolt-2.webp', style: 'movie' },
      { file: 'pictures/black-bolt-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'adam-warlock',
    name: 'Adam Warlock',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/adam-warlock-1.webp', style: 'comic' },
      { file: 'pictures/adam-warlock-2.webp', style: 'movie' },
      { file: 'pictures/adam-warlock-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'squirrel-girl',
    name: 'Squirrel Girl',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/squirrel-girl-1.webp', style: 'comic' },
      { file: 'pictures/squirrel-girl-2.webp', style: 'comic' },
      { file: 'pictures/squirrel-girl-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'blade',
    name: 'Blade',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/blade-1.webp', style: 'comic' },
      { file: 'pictures/blade-2.webp', style: 'movie' },
      { file: 'pictures/blade-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'luke-cage',
    name: 'Luke Cage',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/luke-cage-1.webp', style: 'comic' },
      { file: 'pictures/luke-cage-2.webp', style: 'comic' },
      { file: 'pictures/luke-cage-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'iron-fist',
    name: 'Iron Fist',
    aliases: [],
    tier: 'legend',
    side: 'hero',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/iron-fist-1.webp', style: 'comic' },
      { file: 'pictures/iron-fist-2.webp', style: 'comic' },
      { file: 'pictures/iron-fist-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'm-o-d-o-k',
    name: 'M.O.D.O.K.',
    aliases: ['modok'],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/m-o-d-o-k-1.webp', style: 'comic' },
      { file: 'pictures/m-o-d-o-k-2.webp', style: 'comic' },
      { file: 'pictures/m-o-d-o-k-3.webp', style: 'movie' },
    ],
  },
  {
    id: 'klaw',
    name: 'Klaw',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/klaw-1.webp', style: 'comic' },
      { file: 'pictures/klaw-2.webp', style: 'movie' },
      { file: 'pictures/klaw-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'mister-sinister',
    name: 'Mister Sinister',
    aliases: ['mr sinister'],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/mister-sinister-1.webp', style: 'comic' },
      { file: 'pictures/mister-sinister-2.webp', style: 'comic' },
      { file: 'pictures/mister-sinister-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'annihilus',
    name: 'Annihilus',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/annihilus-1.webp', style: 'comic' },
      { file: 'pictures/annihilus-2.webp', style: 'comic' },
      { file: 'pictures/annihilus-3.webp', style: 'cartoon' },
    ],
  },
  {
    id: 'super-skrull',
    name: 'Super-Skrull',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/super-skrull-1.webp', style: 'comic' },
      { file: 'pictures/super-skrull-2.webp', style: 'comic' },
      { file: 'pictures/super-skrull-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'shadow-king',
    name: 'Shadow King',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/shadow-king-1.webp', style: 'comic' },
      { file: 'pictures/shadow-king-2.webp', style: 'comic' },
      { file: 'pictures/shadow-king-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'arcade',
    name: 'Arcade',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/arcade-1.webp', style: 'comic' },
      { file: 'pictures/arcade-2.webp', style: 'comic' },
      { file: 'pictures/arcade-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'proteus',
    name: 'Proteus',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/proteus-1.webp', style: 'comic' },
      { file: 'pictures/proteus-2.webp', style: 'comic' },
      { file: 'pictures/proteus-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'count-nefaria',
    name: 'Count Nefaria',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/count-nefaria-1.webp', style: 'comic' },
      { file: 'pictures/count-nefaria-2.webp', style: 'comic' },
      { file: 'pictures/count-nefaria-3.webp', style: 'comic' },
    ],
  },
  {
    id: 'hobgoblin',
    name: 'Hobgoblin',
    aliases: [],
    tier: 'legend',
    side: 'villain',
    universe: 'marvel',
    pictures: [
      { file: 'pictures/hobgoblin-1.webp', style: 'comic' },
      { file: 'pictures/hobgoblin-2.webp', style: 'cartoon' },
      { file: 'pictures/hobgoblin-3.webp', style: 'cartoon' },
    ],
  },
];
